### ISSUE TITLE
package.json里面缺少mian字段

### ISSUE THREAD

**Issue by iwege** [medz/id-card-of-china-js#1]
在typescript下面需要指定`id-card-of-china/dist/id-card-china`才能正常获取

**Comment by medz** [comment]
好的，主要是想等国庆还好整合一下资源 尤其是 gbt2206 然后再解决一些地区问题，明天这个问题我提交一下

Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2018年9月26日，22:15，William Ge <notifications@github.com<mailto:notifications@github.com>> 写道：


在typescript下面需要指定id-card-of-china/dist/id-card-china才能正常获取
